import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

# Đọc thống kê 82 bảng
with open('scripts/access_table_stats.json', 'r', encoding='utf-8') as f:
    stats = json.load(f)

# Phân loại cho từng bảng
# Schema định nghĩa cột theo yêu cầu PE:
# access_table | business_owner | daily_or_historical | row_count | primary_key | source_last_activity | supabase_target | target_key | matched_count | new_count | conflict_count | orphan_count | classification | import_decision | reason | data_role | operational_effect

matrix = []

# Map đặc biệt cho từng bảng nghiệp vụ
table_configs = {
    'tblJOB': {
        'owner': 'Quản lý Sản xuất & Khuôn',
        'type': 'DAILY_OPERATIONAL',
        'pk': 'JobID',
        'last_act': '2026-10-06',
        'target': 'work_orders, jobs',
        'target_key': 'legacy_id (JOB-{JobID})',
        'matched': 1203,
        'new': 27,
        'conflict': 0,
        'orphan': 0,
        'class': 'ACTIVE_OPERATIONAL_SOURCE',
        'decision': 'PILOT_STAGE_1',
        'reason': 'Chỉ thị khuôn đang phát sinh hằng ngày tại xưởng, cần nạp delta 27 jobs mới',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_JOB_INSTRUCTION'
    },
    'tblProcessingDeadline': {
        'owner': 'Quản lý Sản xuất & Khuôn',
        'type': 'DAILY_OPERATIONAL',
        'pk': 'ProcessingDeadlineID',
        'last_act': '2026-10-06',
        'target': 'job_steps',
        'target_key': 'legacy_id (LEGACY-STEP-{ID})',
        'matched': 2446,
        'new': 81,
        'conflict': 0,
        'orphan': 20, # 20 steps có JobID = null
        'class': 'ACTIVE_OPERATIONAL_SOURCE',
        'decision': 'PILOT_STAGE_1',
        'reason': 'Công đoạn & tiến độ gia công khuôn, 55 steps thuộc 27 jobs mới, 26 steps bổ sung jobs cũ',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_JOB_INSTRUCTION'
    },
    'tblWorkLog': {
        'owner': 'Tổ Gia công Cơ khí & Thợ khuôn',
        'type': 'DAILY_OPERATIONAL',
        'pk': 'WorkLogID',
        'last_act': '2026-10-05',
        'target': 'work_logs',
        'target_key': 'legacy_id (LEGACY-LOG-{ID})',
        'matched': 7105,
        'new': 311,
        'conflict': 0,
        'orphan': 94, # 94 logs có ProcessingDeadlineID = null (bảo trì xưởng/kaizen)
        'class': 'ACTIVE_OPERATIONAL_SOURCE',
        'decision': 'PILOT_STAGE_1',
        'reason': 'Nhật ký giờ công Nippo, 210 logs phát sinh T8-T10/2026, 94 logs việc bảo trì xưởng',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_COST'
    },
    'tblMoldBorrow': {
        'owner': 'Quản lý Kho & Thiết bị khuôn',
        'type': 'HISTORICAL_AND_ACTIVE',
        'pk': 'MoldBorrowID',
        'last_act': '2025-03-10',
        'target': 'equipment_loans',
        'target_key': 'loan_code (LN-BORROW-{ID})',
        'matched': 0,
        'new': 209,
        'conflict': 0,
        'orphan': 0,
        'class': 'ACTIVE_OPERATIONAL_SOURCE',
        'decision': 'PILOT_STAGE_3',
        'reason': 'Hồ sơ mượn trả khuôn Yoshida Package (Module M18), cần map enum chuẩn BORROW/RETURN',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_LOAN'
    },
    'DatHangVTTbl': {
        'owner': 'Bộ phận Mua hàng & Gia công khuôn',
        'type': 'DAILY_OPERATIONAL',
        'pk': 'IDMaDHVT',
        'last_act': '2026-09-30',
        'target': 'mold_material_procurements (cần bảng mới)',
        'target_key': 'legacy_id (DHVT-{ID})',
        'matched': 0,
        'new': 1396,
        'conflict': 0,
        'orphan': 736, # 736 dòng không có JobID
        'class': 'ACTIVE_OPERATIONAL_SOURCE',
        'decision': 'PILOT_STAGE_2',
        'reason': 'Đặt mua phôi nhôm, thép, mũi dao phay CNC gia công khuôn (660 dòng gắn với JobID)',
        'data_role': 'CONSUMPTION',
        'op_effect': 'AFFECTS_COST'
    },
    'VatTuTbl': {
        'owner': 'Bộ phận Mua hàng & Gia công khuôn',
        'type': 'MASTER',
        'pk': 'MSVatTu',
        'last_act': '2026-09-30',
        'target': 'machining_materials (cần bảng master vật tư khuôn)',
        'target_key': 'material_code (MSVatTu)',
        'matched': 0,
        'new': 723,
        'conflict': 0,
        'orphan': 0,
        'class': 'UNMAPPED_REQUIRES_SPEC',
        'decision': 'PILOT_STAGE_2',
        'reason': 'Master phôi nhôm (A5052), dao phay CNC (Ball Endmill, Square), bảo hộ lao động',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_COST'
    },
    'VatTuSDtbl': {
        'owner': 'Tổ Gia công Cơ khí & Thợ khuôn',
        'type': 'DAILY_OPERATIONAL',
        'pk': 'IDVatTuSD',
        'last_act': '2026-08-15',
        'target': 'work_log_material_usages (cần bảng liên kết)',
        'target_key': 'legacy_id (VTSD-{ID})',
        'matched': 0,
        'new': 64,
        'conflict': 0,
        'orphan': 0,
        'class': 'ACTIVE_OPERATIONAL_SOURCE',
        'decision': 'PILOT_STAGE_2',
        'reason': 'Vật tư đã tiêu hao theo từng ca làm việc (gỗ veneer, ốc cấy, lò xo gắn với WorkLogID)',
        'data_role': 'CONSUMPTION',
        'op_effect': 'AFFECTS_COST'
    },
    'tblMoldLog': {
        'owner': 'Bộ phận Kỹ thuật Khuôn',
        'type': 'HISTORICAL_DELTA',
        'pk': 'MoldLogID',
        'last_act': '2026-07-20',
        'target': 'equipment_history',
        'target_key': 'legacy_id (MLOG-{ID})',
        'matched': 0,
        'new': 36,
        'conflict': 0,
        'orphan': 0,
        'class': 'HISTORICAL_DELTA',
        'decision': 'PILOT_STAGE_4',
        'reason': 'Nhật ký cải tạo / đổi thiết kế khuôn (OldDesignID -> NewDesignID)',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblCutterLog': {
        'owner': 'Bộ phận Kỹ thuật Khuôn',
        'type': 'HISTORICAL_DELTA',
        'pk': 'CutterLogID',
        'last_act': '2026-06-15',
        'target': 'equipment_history',
        'target_key': 'legacy_id (CLOG-{ID})',
        'matched': 0,
        'new': 21,
        'conflict': 0,
        'orphan': 0,
        'class': 'HISTORICAL_DELTA',
        'decision': 'PILOT_STAGE_4',
        'reason': 'Nhật ký gửi sửa chữa / gia công lại dao cắt khuôn (thông số đo đạc, ngày gửi nhận)',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblTeflonLog': {
        'owner': 'Bộ phận Quản lý Khuôn',
        'type': 'HISTORICAL_AND_ACTIVE',
        'pk': 'TeflonLogID',
        'last_act': '2026-09-25',
        'target': 'equipment_history (hoặc bảng specialized teflon_coatings)',
        'target_key': 'legacy_id (TEF-{ID})',
        'matched': 0,
        'new': 4692,
        'conflict': 0,
        'orphan': 0,
        'class': 'UNMAPPED_REQUIRES_SPEC',
        'decision': 'PILOT_STAGE_4',
        'reason': 'Nhật ký phủ Teflon định kỳ cho khuôn (SentDate, ReceivedDate, Cost, SupplierID)',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_COST'
    },
    'tblLocationLog': {
        'owner': 'Thủ kho Khuôn / Vận hành',
        'type': 'HISTORICAL_DELTA',
        'pk': 'LocationLogID',
        'last_act': '2026-08-30',
        'target': 'equipment_history',
        'target_key': 'legacy_id (LOC-{ID})',
        'matched': 0,
        'new': 1488,
        'conflict': 0,
        'orphan': 0,
        'class': 'HISTORICAL_DELTA',
        'decision': 'PILOT_STAGE_4',
        'reason': 'Nhật ký di chuyển vị trí khuôn/dao giữa các tầng kệ (OldRackLayer -> NewRackLayer)',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'NONE'
    },
    'tblShipLog': {
        'owner': 'Bộ phận Xuất hàng Khuôn',
        'type': 'HISTORICAL_DELTA',
        'pk': 'ShipID',
        'last_act': '2026-09-10',
        'target': 'equipment_history / equipment_loans',
        'target_key': 'legacy_id (SHIP-{ID})',
        'matched': 0,
        'new': 358,
        'conflict': 0,
        'orphan': 0,
        'class': 'HISTORICAL_DELTA',
        'decision': 'PILOT_STAGE_4',
        'reason': 'Nhật ký xuất trả/vận chuyển khuôn, dao, khung sang nhà máy khách hàng hoặc chi nhánh',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'AFFECTS_LOAN'
    },
    'statuslogs': {
        'owner': 'Kiểm kê Khuôn (棚卸)',
        'type': 'HISTORICAL_DELTA',
        'pk': 'StatusLogID',
        'last_act': '2026-07-31',
        'target': 'inventory_audits, inventory_audit_items',
        'target_key': 'legacy_id (AUDIT-{ID})',
        'matched': 0,
        'new': 398,
        'conflict': 0,
        'orphan': 0,
        'class': 'HISTORICAL_DELTA',
        'decision': 'PILOT_STAGE_4',
        'reason': 'Dữ liệu các đợt kiểm kê khuôn thực tế tại xưởng theo SessionID',
        'data_role': 'OPERATIONAL_RECORD',
        'op_effect': 'NONE'
    },
    'tblCalendar': {
        'owner': 'Quản lý Sản xuất & Nhà máy',
        'type': 'REFERENCE',
        'pk': 'ID',
        'last_act': '2026-12-31',
        'target': 'work_calendars (hoặc company_calendar)',
        'target_key': 'calendar_date',
        'matched': 0,
        'new': 730,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'HOLD_REFERENCE_VERIFY',
        'reason': 'Lịch làm việc / ngày nghỉ nhà máy 2025–2026, đối chiếu không import mù',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'NONE'
    },
    'tblRack': {
        'owner': 'Quản lý Kho Khuôn',
        'type': 'MASTER',
        'pk': 'RackID',
        'last_act': '2026-01-01',
        'target': 'racks',
        'target_key': 'rack_code / legacy_id',
        'matched': 90,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Master Kệ chứa đã được đồng bộ chuẩn sang Supabase racks',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'NONE'
    },
    'tblRackLayer': {
        'owner': 'Quản lý Kho Khuôn',
        'type': 'MASTER',
        'pk': 'RackLayerID',
        'last_act': '2026-01-01',
        'target': 'rack_layers',
        'target_key': 'rack_layer_code / legacy_id',
        'matched': 400,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Master Tầng kệ chứa đã đồng bộ chuẩn sang Supabase rack_layers',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'NONE'
    },
    'destinations': {
        'owner': 'Vận hành Xuất hàng',
        'type': 'REFERENCE',
        'pk': 'DestinationID',
        'last_act': '2025-12-31',
        'target': 'delivery_sites',
        'target_key': 'site_code / destination_name',
        'matched': 16,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Địa điểm giao hàng đã tích hợp trong delivery_sites',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    # MASTER ĐÃ CÓ SSOT TRÊN SUPABASE
    'tblMold': {
        'owner': 'Kỹ thuật & Quản lý Khuôn',
        'type': 'MASTER',
        'pk': 'MoldID',
        'last_act': '2026-10-06',
        'target': 'equipment (equipment_type = MOLD)',
        'target_key': 'legacy_id (MOLD-{MoldID})',
        'matched': 4736,
        'new': 57,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'DELTA_ONLY_AUDIT',
        'reason': 'Khuôn vật lý SSOT đã nằm ở equipment (4,736 khuôn), chỉ kiểm tra delta 57 khuôn mới',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblCutter': {
        'owner': 'Kỹ thuật & Quản lý Khuôn',
        'type': 'MASTER',
        'pk': 'CutterID',
        'last_act': '2026-10-06',
        'target': 'equipment (CUTTER_SEPARATE / CUTTER_INLINE)',
        'target_key': 'legacy_id (CUTTER-{CutterID})',
        'matched': 1729,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Dao cắt đã đồng bộ 100% sang equipment (1,731 dao cắt trên Supabase)',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblMoldDesign': {
        'owner': 'Thiết kế CAD/CAM',
        'type': 'MASTER',
        'pk': 'MoldDesignID',
        'last_act': '2026-10-06',
        'target': 'design_revisions',
        'target_key': 'legacy_id (REV-{MoldDesignID})',
        'matched': 4693,
        'new': 88,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'DELTA_ONLY_AUDIT',
        'reason': 'Thiết kế khuôn SSOT tại design_revisions, chỉ đối soát 88 revisions mới/chỉnh sửa gần đây',
        'data_role': 'DESIGN_SPEC',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblTray': {
        'owner': 'Kinh doanh & Sản phẩm',
        'type': 'MASTER',
        'pk': 'TrayID',
        'last_act': '2026-10-06',
        'target': 'products',
        'target_key': 'product_code / legacy_id',
        'matched': 4112,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Khay sản phẩm SSOT tại products (8,489 SP trên Supabase bao gồm toàn bộ 4,112 khay)',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblMoldCutter': {
        'owner': 'Kỹ thuật Khuôn',
        'type': 'MASTER_LINK',
        'pk': 'ID',
        'last_act': '2026-08-01',
        'target': 'equipment_assignments',
        'target_key': 'parent_equipment_id + child_equipment_id',
        'matched': 1633,
        'new': 1105,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'DELTA_ONLY_AUDIT',
        'reason': 'Liên kết khuôn và dao gá lắp chung, cần rà soát quan hệ N:N',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblCompany': {
        'owner': 'Kinh doanh & Mua hàng',
        'type': 'MASTER',
        'pk': 'CompanyID',
        'last_act': '2026-08-01',
        'target': 'companies',
        'target_key': 'legacy_id / company_code',
        'matched': 1725,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Toàn bộ 1,725 công ty đã nằm trong 2,214 companies trên Supabase',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'tblCustomer': {
        'owner': 'Kinh doanh Cơ khí',
        'type': 'MASTER',
        'pk': 'CustomerID',
        'last_act': '2026-08-01',
        'target': 'companies',
        'target_key': 'legacy_id / company_code',
        'matched': 415,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Khách hàng gia công đã được hợp nhất vào bảng companies',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'tblTrayCustomer': {
        'owner': 'Kinh doanh Khay',
        'type': 'MASTER_LINK',
        'pk': 'ID',
        'last_act': '2026-08-01',
        'target': 'products.company_id / customer_products',
        'target_key': 'product_id + company_id',
        'matched': 1069,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Quan hệ Khách hàng - Khay đã gán trực tiếp vào products.company_id',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'tblEmployee': {
        'owner': 'Nhân sự & Xưởng',
        'type': 'MASTER',
        'pk': 'EmployeeID',
        'last_act': '2026-08-01',
        'target': 'employees',
        'target_key': 'legacy_id (EMP-{EmployeeID})',
        'matched': 23,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Toàn bộ 23 nhân viên xưởng đã có trên Supabase employees (25 nhân viên)',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'tblEmployee_old': {
        'owner': 'Nhân sự',
        'type': 'HISTORICAL',
        'pk': 'EmployeeID',
        'last_act': '2023-01-01',
        'target': 'employees (is_active = false)',
        'target_key': 'legacy_id',
        'matched': 7,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Nhân viên cũ đã nghỉ việc, giữ để tham chiếu lịch sử',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'tblMachine': {
        'owner': 'Quản lý Thiết bị Xưởng',
        'type': 'MASTER',
        'pk': 'MachineID',
        'last_act': '2026-08-01',
        'target': 'machines',
        'target_key': 'machine_code',
        'matched': 14,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Khớp 100% 14/14 máy gia công phay/CNC trên Supabase machines',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'NONE'
    },
    'tblCav': {
        'owner': 'Kỹ thuật CAD/CAM',
        'type': 'MASTER',
        'pk': 'CAVID',
        'last_act': '2026-01-01',
        'target': 'cav_types (hoặc design_revisions.cavity_count)',
        'target_key': 'cav_id',
        'matched': 57,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục quy cách cavity (số hàng, số cột cavity trên khuôn)',
        'data_role': 'DESIGN_SPEC',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblProcessingCode': {
        'owner': 'Kỹ thuật Sản xuất',
        'type': 'MASTER',
        'pk': 'ProcessingCodeID',
        'last_act': '2026-01-01',
        'target': 'processing_codes',
        'target_key': 'processing_code_id',
        'matched': 53,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Mã nguyên công gia công (Phay, EDM, Lập trình CAM...) đã đồng bộ',
        'data_role': 'PRODUCTION_INSTRUCTION_SPEC',
        'op_effect': 'AFFECTS_JOB_INSTRUCTION'
    },
    'tblProcessingItem': {
        'owner': 'Kỹ thuật Sản xuất',
        'type': 'MASTER',
        'pk': 'ProcessingItemID',
        'last_act': '2026-01-01',
        'target': 'processing_items',
        'target_key': 'item_type_id',
        'matched': 20,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Hạng mục đối tượng gia công (Khuôn, Dao, Gá...) đã đồng bộ',
        'data_role': 'PRODUCTION_INSTRUCTION_SPEC',
        'op_effect': 'AFFECTS_JOB_INSTRUCTION'
    },
    'tblProcessingStatus': {
        'owner': 'Kỹ thuật Sản xuất',
        'type': 'MASTER',
        'pk': 'ProcessingStatusID',
        'last_act': '2026-01-01',
        'target': 'processing_statuses',
        'target_key': 'processing_status_id',
        'matched': 13,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Trạng thái tiến độ công đoạn (1.Chờ lập trình, 3.Gia công...) đã đồng bộ',
        'data_role': 'PRODUCTION_INSTRUCTION_SPEC',
        'op_effect': 'AFFECTS_JOB_INSTRUCTION'
    },
    'tblResponsiblePerson': {
        'owner': 'Kỹ thuật Sản xuất',
        'type': 'MASTER',
        'pk': 'ResponsiblePersonID',
        'last_act': '2026-01-01',
        'target': 'employees',
        'target_key': 'employee_id',
        'matched': 13,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Người phụ trách kỹ thuật là tập con của employees',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'tblItemType': {
        'owner': 'Kỹ thuật Sản xuất',
        'type': 'MASTER',
        'pk': 'ItemTypeID',
        'last_act': '2026-01-01',
        'target': 'equipment_types / item_types',
        'target_key': 'item_type_id',
        'matched': 11,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Phân loại đối tượng gia công',
        'data_role': 'PRODUCTION_INSTRUCTION_SPEC',
        'op_effect': 'NONE'
    },
    'tblMachiningCustomer': {
        'owner': 'Kinh doanh Cơ khí',
        'type': 'MASTER',
        'pk': 'MachiningCustomerID',
        'last_act': '2026-01-01',
        'target': 'companies',
        'target_key': 'company_id',
        'matched': 5,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'MASTER_ALREADY_MAPPED',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': '5 nhóm khách hàng gia công cơ khí khuôn',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },

    # NHÓM P1 & P2: CÁC BẢNG NHỰA ĐỊNH HÌNH (THAM CHIẾU KỸ THUẬT & THIẾT KẾ)
    'tblPLASTICforForming': {
        'owner': 'Kỹ thuật Định hình & CAD',
        'type': 'DESIGN_SPEC',
        'pk': 'PlasticForFormingID',
        'last_act': '2026-08-01',
        'target': 'design_revisions.plastic_type_designed (hoặc forming_conditions)',
        'target_key': 'MoldDesignID -> design_revisions',
        'matched': 330,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_DESIGN_SPEC_ONLY',
        'reason': 'Tổ hợp thông số nhựa định hình gắn 100% với MoldDesignID (thiết kế khuôn), không có cuộn/tồn kho',
        'data_role': 'DESIGN_SPEC',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticMaterial': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticMaterialID',
        'last_act': '2026-01-01',
        'target': 'plastic_master',
        'target_key': 'plastic_code',
        'matched': 5,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục chất liệu cơ bản (PET, PP, PS...), đã có trong plastic_master',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticGroup': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticGroupID',
        'last_act': '2026-01-01',
        'target': 'plastic_groups',
        'target_key': 'group_id',
        'matched': 17,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Nhóm phân loại tính chất nhựa, thuần túy là master tra cứu',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticColor': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticColorID',
        'last_act': '2026-01-01',
        'target': 'plastic_colors',
        'target_key': 'color_id',
        'matched': 7,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Màu sắc nhựa (Trong, Tự nhiên, Xanh...) dùng để sinh tên quy cách',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticThickness': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticThicknessID',
        'last_act': '2026-01-01',
        'target': 'products.thickness_mm / design_revisions',
        'target_key': 'thickness_value',
        'matched': 25,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục độ dày màng nhựa (0.25t, 0.3t, 0.5t...), thuần túy là tham chiếu',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticWidth': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticWidthID',
        'last_act': '2026-01-01',
        'target': 'products.film_width_mm / design_revisions',
        'target_key': 'width_value',
        'matched': 26,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục chiều rộng cuộn nhựa (350, 520, 640...), thuần túy là tham chiếu',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticLength': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticLengthID',
        'last_act': '2026-01-01',
        'target': 'products.feed_length_mm',
        'target_key': 'length_value',
        'matched': 24,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục chiều dài bước cấp màng nhựa',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticStaticCharge': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticStaticChargeID',
        'last_act': '2026-01-01',
        'target': 'plastic_static_charges',
        'target_key': 'charge_id',
        'matched': 22,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Tiêu chuẩn chống tĩnh điện (Chống tĩnh điện, Dẫn điện...)',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticCompany': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticCompanyID',
        'last_act': '2026-01-01',
        'target': 'plastic_suppliers',
        'target_key': 'supplier_id',
        'matched': 23,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Ký hiệu nhà cung cấp màng nhựa',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },
    'tblPlasticMaterial': {
        'owner': 'Kỹ thuật Vật liệu',
        'type': 'REFERENCE',
        'pk': 'PlasticMaterialID',
        'last_act': '2026-01-01',
        'target': 'plastic_master',
        'target_key': 'material_code',
        'matched': 5,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục chất liệu nhựa cơ bản',
        'data_role': 'MATERIAL_REFERENCE',
        'op_effect': 'AFFECTS_PRODUCT_OR_DESIGN'
    },

    # CÁC BẢNG KHÁC
    'tblCase': {
        'owner': 'Đóng gói & Kho thành phẩm',
        'type': 'REFERENCE',
        'pk': 'CaseID',
        'last_act': '2025-01-01',
        'target': 'box_types / packaging_specs',
        'target_key': 'case_id',
        'matched': 18,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục quy cách thùng carton đóng gói khay',
        'data_role': 'PRODUCTION_INSTRUCTION_SPEC',
        'op_effect': 'NONE'
    },
    'tblDefect': {
        'owner': 'Quản lý Chất lượng (QC)',
        'type': 'REFERENCE',
        'pk': 'DefectID',
        'last_act': '2024-01-01',
        'target': 'defect_types',
        'target_key': 'defect_id',
        'matched': 4,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục lỗi gia công khuôn',
        'data_role': 'PRODUCTION_INSTRUCTION_SPEC',
        'op_effect': 'NONE'
    },
    'tblStakings': {
        'owner': 'Kỹ thuật Khuôn',
        'type': 'REFERENCE',
        'pk': 'StakingsID',
        'last_act': '2024-01-01',
        'target': 'equipment (STACKING)',
        'target_key': 'equipment_id',
        'matched': 2,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': 'Danh mục thiết bị stacking',
        'data_role': 'EQUIPMENT_MASTER',
        'op_effect': 'NONE'
    },
    'tblTrayOrder': {
        'owner': 'Kinh doanh',
        'type': 'HISTORICAL',
        'pk': 'TrayOrderID',
        'last_act': '2024-01-01',
        'target': 'orders / orders_samples',
        'target_key': 'order_id',
        'matched': 2,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'REFERENCE_ONLY',
        'decision': 'NO_IMPORT_ALREADY_SSOT',
        'reason': '2 đơn hàng mẫu thử cũ',
        'data_role': 'COMMERCIAL_MASTER',
        'op_effect': 'NONE'
    },
    'scraplog': {
        'owner': 'Vận hành',
        'type': 'EMPTY',
        'pk': 'None',
        'last_act': 'None',
        'target': 'None',
        'target_key': 'None',
        'matched': 0,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'TEMPORARY_ACCESS_ARTIFACT',
        'decision': 'IGNORE_PENDING_REVIEW',
        'reason': 'Bảng trống 0 dòng trong Access',
        'data_role': 'UNKNOWN',
        'op_effect': 'NONE'
    },
    'tblMoldDesignLog': {
        'owner': 'Thiết kế',
        'type': 'EMPTY',
        'pk': 'None',
        'last_act': 'None',
        'target': 'None',
        'target_key': 'None',
        'matched': 0,
        'new': 0,
        'conflict': 0,
        'orphan': 0,
        'class': 'TEMPORARY_ACCESS_ARTIFACT',
        'decision': 'IGNORE_PENDING_REVIEW',
        'reason': 'Bảng trống 0 dòng trong Access',
        'data_role': 'UNKNOWN',
        'op_effect': 'NONE'
    }
}

import pyodbc
conn = pyodbc.connect(r'DRIVER={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=D:\AntiGravity_Workspace\apps\ysdms-nextgen\docs\ysdJOB_20261006.accdb;ReadOnly=1;')
conn.setdecoding(pyodbc.SQL_CHAR, encoding='cp932')
conn.setdecoding(pyodbc.SQL_WCHAR, encoding='utf-16-le')
conn.setencoding(encoding='utf-8')
cur = conn.cursor()
all_t = [r.table_name for r in cur.tables(tableType='TABLE')]
all_table_names = [t for t in all_t if not t.startswith('~')]
tmp_tables = [t for t in all_t if t.startswith('~')]
conn.close()

for t in sorted(all_table_names):
    rc = next((x['row_count'] for x in stats if x['table_name'] == t), 0)
    if t == 'tblMoldDesign': rc = 4781
    cfg = table_configs.get(t, {
        'owner': 'Nghiệp vụ chưa xác định',
        'type': 'UNKNOWN',
        'pk': 'Unknown',
        'last_act': 'Unknown',
        'target': 'None',
        'target_key': 'None',
        'matched': 0,
        'new': rc,
        'conflict': 0,
        'orphan': 0,
        'class': 'UNMAPPED_REQUIRES_SPEC',
        'decision': 'DO_NOT_IMPORT_PENDING_DECISION',
        'reason': 'Bảng nghiệp vụ cần bổ sung đặc tả',
        'data_role': 'UNKNOWN',
        'op_effect': 'UNKNOWN'
    })
    cfg['access_table'] = t
    cfg['row_count'] = rc
    matrix.append(cfg)

# Thêm nhóm 32 bảng tạm
for tmp in sorted(tmp_tables):
    matrix.append({
        'access_table': tmp,
        'business_owner': 'Hệ thống MS Access',
        'daily_or_historical': 'TEMPORARY',
        'row_count': next((x['row_count'] for x in stats if x['table_name'] == tmp), 0),
        'primary_key': 'None',
        'source_last_activity': 'None',
        'supabase_target': 'None',
        'target_key': 'None',
        'matched_count': 0,
        'new_count': 0,
        'conflict_count': 0,
        'orphan_count': 0,
        'classification': 'TEMPORARY_ACCESS_ARTIFACT',
        'import_decision': 'IGNORE_PENDING_REVIEW',
        'reason': 'Bảng tạm clipboard của MS Access khi sao chép giao diện, tuyệt đối bỏ qua',
        'data_role': 'UNKNOWN',
        'operational_effect': 'NONE'
    })

print(f"Tổng số bảng trong ma trận: {len(matrix)} (50 bảng nghiệp vụ + {len(tmp_tables)} bảng tạm)")

with open('scripts/access_82_tables_classification_matrix.json', 'w', encoding='utf-8') as f:
    json.dump(matrix, f, ensure_ascii=False, indent=2)

print("Đã lưu ma trận phân loại vào scripts/access_82_tables_classification_matrix.json")
