import { StyleSheet } from '@react-pdf/renderer';

export const deliveryNoteStyles = StyleSheet.create({
  page: {
    fontFamily: 'NotoSansJP',
    fontSize: 8.5,
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 26,
    backgroundColor: '#ffffff',
    lineHeight: 1.3,
    color: '#0f172a',
  },
  sectionBox: {
    borderWidth: 1,
    borderColor: '#94a3b8',
    padding: 9,
    borderRadius: 3,
    position: 'relative',
    height: 382,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  titleBlock: {
    alignItems: 'center',
    marginBottom: 6,
  },
  mainTitle: {
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: 6,
    color: '#0f172a',
    borderBottomWidth: 1.5,
    borderBottomColor: '#0f172a',
    paddingBottom: 2,
  },
  customerBox: {
    width: '54%',
    borderBottomWidth: 1,
    borderBottomColor: '#64748b',
    paddingBottom: 4,
  },
  customerName: {
    fontSize: 12,
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: 2,
  },
  deliverySiteName: {
    fontSize: 8.5,
    color: '#334155',
    marginBottom: 2,
  },
  subDetails: {
    marginTop: 3,
    fontSize: 7.5,
    color: '#475569',
  },
  companyInfoBox: {
    width: '44%',
    fontSize: 7.5,
    lineHeight: 1.25,
    textAlign: 'right',
    alignItems: 'flex-end',
  },
  companyLogoText: {
    fontSize: 11,
    fontWeight: 700,
    color: '#0066CC',
    letterSpacing: 0.5,
  },
  companyName: {
    fontSize: 9.5,
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: 1,
  },
  sealAreaRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 4,
    gap: 6,
  },
  sealBox: {
    width: 34,
    height: 34,
    borderWidth: 1,
    borderColor: '#94a3b8',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingTop: 2,
  },
  sealLabel: {
    fontSize: 6,
    color: '#64748b',
  },
  receiptStampBox: {
    width: 38,
    height: 38,
    borderWidth: 1.5,
    borderColor: '#dc2626',
    backgroundColor: '#fff5f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  receiptStampLabel: {
    fontSize: 7,
    fontWeight: 700,
    color: '#dc2626',
  },
  stampImage: {
    width: 36,
    height: 36,
  },
  table: {
    width: '100%',
    marginVertical: 4,
    borderWidth: 1,
    borderColor: '#94a3b8',
  },
  tableHeaderRow: {
    flexDirection: 'row',
    backgroundColor: '#f1f5f9',
    borderBottomWidth: 1,
    borderBottomColor: '#94a3b8',
    paddingVertical: 3,
    fontWeight: 700,
  },
  tableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingVertical: 3,
    minHeight: 16,
    alignItems: 'center',
  },
  colNo: { width: '6%', textAlign: 'center', fontSize: 7.5 },
  colCode: { width: '22%', paddingLeft: 4, fontSize: 8 },
  colName: { width: '38%', paddingLeft: 4, fontSize: 8 },
  colQty: { width: '16%', textAlign: 'right', paddingRight: 6, fontSize: 8.5, fontWeight: 700 },
  colUnit: { width: '8%', textAlign: 'center', fontSize: 8 },
  colBox: { width: '10%', textAlign: 'center', fontSize: 7.5 },

  notesAndQrRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderTopWidth: 0.5,
    borderTopColor: '#cbd5e1',
    paddingTop: 4,
    marginTop: 2,
  },
  notesBox: {
    flex: 1,
    paddingRight: 8,
    fontSize: 7.5,
    color: '#334155',
  },
  qrBox: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrImage: {
    width: 44,
    height: 44,
  },

  footerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 7.5,
    color: '#475569',
    marginTop: 2,
    borderTopWidth: 0.5,
    borderTopColor: '#e2e8f0',
    paddingTop: 3,
  },
  cutLineContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 6,
    position: 'relative',
  },
  cutLine: {
    position: 'absolute',
    left: 0,
    right: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#94a3b8',
    borderStyle: 'dashed',
  },
  cutBadge: {
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    fontSize: 7.5,
    color: '#64748b',
  },
});
