import csv, os, uuid, json

SOURCE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_DIR = os.path.join(SOURCE_DIR, "source_data", "csv-access-data")
OUTPUT_FILE = os.path.join(SOURCE_DIR, "supabase", "migrations", "20260612000002_068_seed_legacy_v4_master.sql")

def read_csv(filename):
    path = os.path.join(CSV_DIR, filename)
    if not os.path.exists(path):
        print(f"  [SKIP] {filename} not found")
        return []
    with open(path, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))
    print(f"  [OK] {filename}: {len(rows)} rows")
    return rows

def esc(val):
    if not val or str(val).strip() in ("", "nan", "None"): return "NULL"
    s = str(val).strip()
    if "$$" in s: s = s.replace("$$", "$ $")
    return f"$${s}$$"

def num(val):
    if not val or str(val).strip() in ("", "nan", "None"): return "NULL"
    try: return str(float(str(val).strip()))
    except: return "NULL"

def integer(val):
    if not val or str(val).strip() in ("", "nan", "None"): return "NULL"
    try: return str(int(float(str(val).strip())))
    except: return "NULL"

def boolean(val):
    v = str(val).strip().upper() if val else ""
    return "true" if v in ("TRUE", "1", "YES", "-1") else "false"

def to_json(d):
    clean = {k: v for k, v in d.items() if v and str(v).strip() not in ("", "nan", "None")}
    if not clean: return "NULL"
    return esc(json.dumps(clean, ensure_ascii=False))

def main():
    print("=== YSDMS Seed V4 (Master Architecture) Generator ===")
    f = open(OUTPUT_FILE, "w", encoding="utf-8")
    f.write("-- YSDMS NextGen Legacy Data Import (V4 MASTER ARCHITECTURE)\n")
    f.write("-- Generated by generate_seed_v4_master.py\n")
    f.write("-- IMPORTANT: Run 067_schema_v2_to_v3.sql FIRST\n\n")
    f.write("BEGIN;\n\n")

    comp_map = {}   # old CompanyID -> new UUID (Suppliers/Keepers)
    cust_map = {}   # old CustomerID -> new UUID (Owners)
    emp_map = {}
    rack_map = {}
    rl_map = {}
    tray_map = {}       # TrayID -> Product UUID
    master_map = {}     # MoldMasterID -> MoldMaster UUID
    design_map = {}     # MoldDesignID -> DesignRevision UUID
    revision_map = {}   # MoldRevisionID -> MoldRevision UUID

    # Build relationship mappings from MoldRevision to connect Design -> Master
    # moldrevision.csv: MoldRevisionID, MoldMasterID, MoldDesignID
    design_to_master = {}
    for r in read_csv("moldrevision.csv"):
        m_id = r.get("MoldMasterID")
        d_id = r.get("MoldDesignID")
        if m_id and d_id:
            design_to_master[d_id] = m_id

    # [1] COMPANIES (from companies.csv)
    f.write("-- [1] COMPANIES (Suppliers/Outsource)\n")
    for r in read_csv("companies.csv"):
        oid = r.get("CompanyID")
        if not oid: continue
        uid = str(uuid.uuid4())
        comp_map[oid] = uid
        code = r.get("CompanyShortName") or f"COMP-{oid}"
        name = r.get("CompanyName") or code
        f.write(f"INSERT INTO companies (company_id, company_code, company_name, company_type, "
                f"address, tel, fax, order_folder_path, cad_folder_path, notes, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, '{{SUPPLIER,OUTSOURCE}}', "
                f"{esc(r.get('CompanyAddress'))}, {esc(r.get('CompanyTEL'))}, {esc(r.get('CompanyFAX'))}, "
                f"{esc(r.get('OrderFolderPath'))}, {esc(r.get('CadFolderPath'))}, "
                f"{esc(r.get('CompanyNotes'))}, {esc('COMP-'+oid)}"
                f") ON CONFLICT (company_code) DO NOTHING;\n")
    f.write("\n")

    # [1b] CUSTOMERS (from customers.csv) -> COMPANIES
    f.write("-- [1b] COMPANIES (Customers)\n")
    for r in read_csv("customers.csv"):
        oid = r.get("CustomerID")
        if not oid: continue
        uid = str(uuid.uuid4())
        cust_map[oid] = uid
        code = r.get("CustomerShortName") or f"CUST-{oid}"
        name = r.get("CustomerRomajiName") or r.get("CustomerKanaName") or code
        f.write(f"INSERT INTO companies (company_id, company_code, company_name, company_name_romaji, company_type, "
                f"notes, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, {esc(r.get('CustomerRomajiName'))}, '{{CUSTOMER}}', "
                f"{esc(r.get('CustomerNotes'))}, {esc('CUST-'+oid)}"
                f") ON CONFLICT (company_code) DO NOTHING;\n")
    f.write("\n")

    # [2] EMPLOYEES
    f.write("-- [2] EMPLOYEES\n")
    for r in read_csv("employees.csv"):
        oid = r.get("EmployeeID")
        if not oid: continue
        uid = str(uuid.uuid4())
        emp_map[oid] = uid
        name = r.get("EmployeeName") or "Unknown"
        f.write(f"INSERT INTO employees (employee_id, employee_code, employee_name, legacy_id) VALUES ("
                f"'{uid}', {esc('EMP-'+oid)}, {esc(name)}, {esc('EMP-'+oid)}"
                f") ON CONFLICT (employee_code) DO NOTHING;\n")
    f.write("\n")

    # [3] RACKS + RACK_LAYERS
    f.write("-- [3] RACKS\n")
    seen_rack_codes = {}
    for r in read_csv("racks.csv"):
        oid = r.get("RackID")
        if not oid: continue
        code = r.get("RackSymbol") or r.get("RackNumber") or f"R-{oid}"
        name = r.get("RackName") or r.get("RackLocation") or code
        if code in seen_rack_codes:
            rack_map[oid] = seen_rack_codes[code]
            continue
        uid = str(uuid.uuid4())
        rack_map[oid] = uid
        seen_rack_codes[code] = uid
        f.write(f"INSERT INTO racks (rack_id, rack_code, rack_name, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, {esc('RACK-'+oid)}"
                f") ON CONFLICT (rack_code) DO NOTHING;\n")
    
    seen_layer_codes = {}
    for r in read_csv("racklayers.csv"):
        oid = r.get("RackLayerID")
        rack_oid = r.get("RackID")
        if not oid or not rack_oid or rack_oid not in rack_map: continue
        rack_uid = rack_map[rack_oid]
        lcode = r.get("LayerSymbol") or r.get("LayerNumber") or f"L-{oid}"
        if (rack_uid, lcode) in seen_layer_codes:
            rl_map[oid] = seen_layer_codes[(rack_uid, lcode)]
            continue
        uid = str(uuid.uuid4())
        rl_map[oid] = uid
        seen_layer_codes[(rack_uid, lcode)] = uid
        f.write(f"INSERT INTO rack_layers (layer_id, rack_id, layer_code, legacy_id) VALUES ("
                f"'{uid}', '{rack_uid}', {esc(lcode)}, {esc('LAYER-'+oid)}"
                f") ON CONFLICT (rack_id, layer_code) DO NOTHING;\n")
    f.write("\n")

    # [4] PRODUCTS (from tray.csv)
    f.write("-- [4] PRODUCTS\n")
    for r in read_csv("tray.csv"):
        oid = r.get("TrayID")
        if not oid: continue
        uid = str(uuid.uuid4())
        tray_map[oid] = uid
        code = r.get("TrayCode") or f"TRAY-{oid}"
        name = r.get("TrayName") or code
        cust_uid = cust_map.get(r.get("CustomerID"))
        if not cust_uid: continue # company_id is NOT NULL in Supabase
        
        legacy_specs = to_json({
            "MoldTrayName": r.get("MoldTrayName"),
            "CustomerTrayName": r.get("CustomerTrayName"),
            "TrayWeight": r.get("TrayWeight")
        })

        f.write(f"INSERT INTO products (product_id, product_code, product_name, company_id, "
                f"notes, legacy_id, legacy_specs) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, '{cust_uid}', "
                f"{esc(r.get('TrayOrderNotes'))}, {esc('TRAY-'+oid)}, {legacy_specs}"
                f") ON CONFLICT (product_code) DO NOTHING;\n")
    f.write("\n")

    # [5] MOLD_MASTERS
    f.write("-- [5] MOLD MASTERS\n")
    for r in read_csv("moldmaster.csv"):
        oid = r.get("MoldMasterID")
        if not oid: continue
        uid = str(uuid.uuid4())
        master_map[oid] = uid
        code = r.get("MoldMasterCode") or f"MM-{oid}"
        name = r.get("MoldMasterName") or code
        
        cust_uid = cust_map.get(r.get("CustomerID"), 'NULL')
        tray_uid = tray_map.get(r.get("TrayID"), 'NULL')
        
        f.write(f"INSERT INTO mold_masters (mold_master_id, mold_master_code, mold_master_name, "
                f"company_id, product_id, mold_class, notes, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, "
                f"{repr(cust_uid) if cust_uid != 'NULL' else 'NULL'}, "
                f"{repr(tray_uid) if tray_uid != 'NULL' else 'NULL'}, "
                f"{esc(r.get('MoldClass'))}, {esc(r.get('Notes'))}, {esc('MASTER-'+oid)}"
                f") ON CONFLICT (mold_master_code) DO NOTHING;\n")
    f.write("\n")

    # [6] DESIGN_REVISIONS
    f.write("-- [6] DESIGN REVISIONS\n")
    for r in read_csv("molddesign.csv"):
        oid = r.get("MoldDesignID")
        if not oid: continue
        uid = str(uuid.uuid4())
        design_map[oid] = uid
        code = r.get("MoldDesignCode") or f"MD-{oid}"
        
        cust_uid = cust_map.get(r.get("CustomerID"), 'NULL')
        master_oid = design_to_master.get(oid)
        master_uid = master_map.get(master_oid) if master_oid else 'NULL'

        f.write(f"INSERT INTO design_revisions (revision_id, design_code, mold_master_id, company_id, "
                f"design_length, design_width, design_height, design_depth, design_weight, "
                f"cavity_count, corner_r, chamfer_c, draft_angle, pitch_mm, "
                f"orientation, setup_type, has_separate_cutter, "
                f"customer_tray_name, customer_equipment_no, customer_drawing_no, "
                f"cad_folder_path, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, "
                f"{repr(master_uid) if master_uid != 'NULL' else 'NULL'}, "
                f"{repr(cust_uid) if cust_uid != 'NULL' else 'NULL'}, "
                f"{num(r.get('MoldDesignLength'))}, {num(r.get('MoldDesignWidth'))}, "
                f"{num(r.get('MoldDesignHeight'))}, {num(r.get('MoldDesignDepth'))}, {esc(r.get('MoldDesignWeight'))}, "
                f"{integer(r.get('PieceCount'))}, {esc(r.get('CornerR'))}, {esc(r.get('ChamferC'))}, "
                f"{esc(r.get('DraftAngle'))}, {num(r.get('Pitch'))}, "
                f"{esc(r.get('MoldOrientation'))}, {esc(r.get('MoldSetupType'))}, {boolean(r.get('SeparateCutter'))}, "
                f"{esc(r.get('CustomerTrayName'))}, {esc(r.get('CustomerEquipmentNo'))}, {esc(r.get('CustomerDrawingNo'))}, "
                f"{esc(r.get('DataInput'))}, {esc('DESIGN-'+oid)}"
                f") ON CONFLICT (design_code) DO NOTHING;\n")
    f.write("\n")

    # [7] MOLD_REVISIONS
    f.write("-- [7] MOLD REVISIONS\n")
    for r in read_csv("moldrevision.csv"):
        oid = r.get("MoldRevisionID")
        if not oid: continue
        uid = str(uuid.uuid4())
        revision_map[oid] = uid
        
        master_uid = master_map.get(r.get("MoldMasterID"), 'NULL')
        design_uid = design_map.get(r.get("MoldDesignID"), 'NULL')
        code = r.get("RevisionNo") or f"REV-{oid}"
        name = r.get("RevisionName") or code

        f.write(f"INSERT INTO mold_revisions (mold_revision_id, mold_master_id, design_revision_id, "
                f"revision_code, revision_name, legacy_id) VALUES ("
                f"'{uid}', "
                f"{repr(master_uid) if master_uid != 'NULL' else 'NULL'}, "
                f"{repr(design_uid) if design_uid != 'NULL' else 'NULL'}, "
                f"{esc(code)}, {esc(name)}, {esc('MREV-'+oid)}"
                f") ON CONFLICT (revision_code) DO NOTHING;\n")
    f.write("\n")

    # [8] PHYSICAL MOLDS
    f.write("-- [8] PHYSICAL MOLDS\n")
    for r in read_csv("molds.csv"):
        oid = r.get("MoldID")
        if not oid: continue
        uid = str(uuid.uuid4())
        
        code = r.get("MoldCode") or f"PHY-{oid}"
        name = r.get("MoldName") or code
        
        rev_uid = revision_map.get(r.get("MoldRevisionID"), 'NULL')
        keeper_uid = comp_map.get(r.get("KeeperCompany"), 'NULL')
        layer_uid = rl_map.get(r.get("RackLayerID"), 'NULL')

        f.write(f"INSERT INTO physical_molds (physical_mold_id, system_code, display_name, "
                f"mold_revision_id, keeper_company_id, current_rack_layer_id, "
                f"actual_length_mm, actual_width_mm, actual_height_mm, actual_weight, "
                f"device_status, usage_status, notes, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, "
                f"{repr(rev_uid) if rev_uid != 'NULL' else 'NULL'}, "
                f"{repr(keeper_uid) if keeper_uid != 'NULL' else 'NULL'}, "
                f"{repr(layer_uid) if layer_uid != 'NULL' else 'NULL'}, "
                f"{num(r.get('MoldLengthModified'))}, {num(r.get('MoldWidthModified'))}, "
                f"{num(r.get('MoldHeightModified'))}, {esc(r.get('MoldWeight'))}, "
                f"{esc(r.get('DeviceStatus'))}, {esc(r.get('MoldUsageStatus'))}, "
                f"{esc(r.get('MoldNotes'))}, {esc('MOLD-'+oid)}"
                f") ON CONFLICT (system_code) DO NOTHING;\n")
    f.write("\n")

    # [9] JOBS
    f.write("-- [9] JOBS\n")
    for r in read_csv("jobs.csv"):
        oid = r.get("JobID")
        if not oid: continue
        uid = str(uuid.uuid4())
        
        code = r.get("JobCode") or f"JOB-{oid}"
        name = r.get("JobName") or code
        
        # company_id is outsource company or machining customer -> use comp_map OR cust_map
        machining_cust_oid = r.get("MachiningCustomerID")
        comp_uid = comp_map.get(machining_cust_oid) or cust_map.get(machining_cust_oid) or 'NULL'
        
        design_uid = design_map.get(r.get("MoldDesignID"), 'NULL')
        resp_uid = emp_map.get(r.get("ResponsiblePersonID"), 'NULL')
        
        f.write(f"INSERT INTO jobs (job_id, job_code, job_name, company_id, design_revision_id, responsible_id, "
                f"estimated_hours, job_status, notes, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, "
                f"{repr(comp_uid) if comp_uid != 'NULL' else 'NULL'}, "
                f"{repr(design_uid) if design_uid != 'NULL' else 'NULL'}, "
                f"{repr(resp_uid) if resp_uid != 'NULL' else 'NULL'}, "
                f"{num(r.get('JobQuantity'))}, 'IN_PROGRESS', "
                f"{esc(r.get('JobNote'))}, {esc('JOB-'+oid)}"
                f") ON CONFLICT (job_code) DO NOTHING;\n")
    f.write("\n")

    f.write("COMMIT;\n")
    print("Done!")

if __name__ == "__main__":
    main()
