"""
YSDMS NextGen - Legacy Data Migration Script V3
Generates SQL to import CSV data into schema V3
Run: python scratch/generate_seed_v3.py
Output: supabase/migrations/20260612000002_068_seed_legacy_v3.sql
"""
import csv, os, uuid, json

SOURCE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_DIR = os.path.join(SOURCE_DIR, "source_data", "csv-access-data")
OUTPUT_FILE = os.path.join(SOURCE_DIR, "supabase", "migrations", "20260612000002_068_seed_legacy_v3.sql")

def read_csv(filename):
    path = os.path.join(CSV_DIR, filename)
    if not os.path.exists(path):
        print(f"  [SKIP] {filename} not found")
        return []
    with open(path, newline="", encoding="utf-8-sig") as f:
        rows = list(csv.DictReader(f))
    print(f"  [OK] {filename}: {len(rows)} rows")
    return rows

def esc(val):
    """SQL-safe string with dollar quoting"""
    if not val or str(val).strip() in ("", "nan", "None"): return "NULL"
    s = str(val).strip()
    if "$$" in s: s = s.replace("$$", "$ $")
    return f"$${s}$$"

def num(val):
    if not val or str(val).strip() in ("", "nan", "None"): return "NULL"
    try: return str(float(str(val).strip()))
    except: return "NULL"

def integer(val):
    if not val or str(val).strip() in ("", "nan", "None"): return "NULL"
    try: return str(int(float(str(val).strip())))
    except: return "NULL"

def boolean(val):
    v = str(val).strip().upper() if val else ""
    return "true" if v in ("TRUE", "1", "YES", "-1") else "false"

def to_json(d):
    """Convert dict to SQL JSONB literal"""
    clean = {k: v for k, v in d.items() if v and str(v).strip() not in ("", "nan", "None")}
    if not clean: return "NULL"
    return esc(json.dumps(clean, ensure_ascii=False))

def main():
    print("=== YSDMS Seed V3 Generator ===")
    f = open(OUTPUT_FILE, "w", encoding="utf-8")
    f.write("-- YSDMS NextGen Legacy Data Import (V3)\n")
    f.write("-- Generated by generate_seed_v3.py\n")
    f.write("-- IMPORTANT: Run 067_schema_v2_to_v3.sql FIRST\n\n")
    f.write("BEGIN;\n\n")

    comp_map = {}   # old CompanyID -> new UUID
    emp_map = {}    # old EmployeeID -> new UUID
    rack_map = {}   # old RackID -> new UUID
    rl_map = {}     # old RackLayerID -> new UUID
    design_map = {} # old MoldDesignID -> {mold_master_id, design_rev_id, product_id}
    keeper_map = {} # KeeperCompany text -> company UUID

    # ======================================================================
    # [1] COMPANIES
    # ======================================================================
    f.write("-- [1] COMPANIES\n")
    for r in read_csv("companies.csv"):
        oid = r.get("CompanyID")
        if not oid: continue
        uid = str(uuid.uuid4())
        comp_map[oid] = uid

        code = r.get("CompanyShortName") or f"COMP-{oid}"
        name = r.get("CompanyName") or code

        f.write(f"INSERT INTO companies (company_id, company_code, company_name, company_type, "
                f"address, tel, fax, order_folder_path, cad_folder_path, notes, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, '{{CUSTOMER}}', "
                f"{esc(r.get('CompanyAddress'))}, {esc(r.get('CompanyTEL'))}, {esc(r.get('CompanyFAX'))}, "
                f"{esc(r.get('OrderFolderPath'))}, {esc(r.get('CadFolderPath'))}, "
                f"{esc(r.get('CompanyNotes'))}, {esc(oid)}"
                f") ON CONFLICT (company_code) DO UPDATE SET legacy_id=EXCLUDED.legacy_id;\n")
    f.write("\n")

    # ======================================================================
    # [2] EMPLOYEES
    # ======================================================================
    f.write("-- [2] EMPLOYEES\n")
    for r in read_csv("employees.csv"):
        oid = r.get("EmployeeID")
        if not oid: continue
        uid = str(uuid.uuid4())
        emp_map[oid] = uid
        name = r.get("EmployeeName") or "Unknown"
        f.write(f"INSERT INTO employees (employee_id, employee_code, employee_name, legacy_id) VALUES ("
                f"'{uid}', {esc('EMP-'+oid)}, {esc(name)}, {esc(oid)}"
                f") ON CONFLICT (employee_code) DO NOTHING;\n")
    f.write("\n")

    # ======================================================================
    # [3] RACKS + RACK_LAYERS
    # ======================================================================
    f.write("-- [3] RACKS\n")
    seen_rack_codes = {}  # rack_code -> UUID (to handle duplicates)
    for r in read_csv("racks.csv"):
        oid = r.get("RackID")
        if not oid: continue
        code = r.get("RackSymbol") or r.get("RackNumber") or f"R-{oid}"
        name = r.get("RackName") or r.get("RackLocation") or code

        if code in seen_rack_codes:
            # Duplicate rack_code: reuse the UUID of the first occurrence
            rack_map[oid] = seen_rack_codes[code]
            continue

        uid = str(uuid.uuid4())
        rack_map[oid] = uid
        seen_rack_codes[code] = uid
        f.write(f"INSERT INTO racks (id, rack_code, rack_name, location_in_factory, legacy_id) VALUES ("
                f"'{uid}', {esc(code)}, {esc(name)}, {esc(r.get('RackLocation'))}, {esc(oid)}"
                f") ON CONFLICT (rack_code) DO UPDATE SET legacy_id=EXCLUDED.legacy_id;\n")
    f.write("\n")

    f.write("-- [3b] RACK_LAYERS\n")
    seen_layer_codes = set()
    for r in read_csv("racklayers.csv"):
        oid = r.get("RackLayerID")
        if not oid: continue
        rack_uid = rack_map.get(r.get("RackID"))
        if not rack_uid: continue
        layer_num = integer(r.get("RackLayerNumber"))
        if layer_num == "NULL": continue
        layer_code = f"RL-{oid}"
        if layer_code in seen_layer_codes:
            continue  # skip duplicate layer_code
        seen_layer_codes.add(layer_code)
        uid = str(uuid.uuid4())
        rl_map[oid] = uid
        f.write(f"INSERT INTO rack_layers (id, rack_id, layer_number, layer_code, notes, legacy_id) VALUES ("
                f"'{uid}', '{rack_uid}', {layer_num}, {esc(layer_code)}, "
                f"{esc(r.get('RackLayerNotes'))}, {esc(oid)}"
                f") ON CONFLICT (layer_code) DO NOTHING;\n")
    f.write("\n")

    # Helper: get or create keeper company
    def get_keeper_id(keeper_text):
        if not keeper_text or str(keeper_text).strip() in ("", "nan", "None"): return "NULL"
        keeper_text = str(keeper_text).strip()
        if keeper_text in keeper_map:
            return f"'{keeper_map[keeper_text]}'"
        # Check if exists in comp_map by name
        for oid, uid in comp_map.items():
            pass  # Can't match by name in generated SQL, so create new
        uid = str(uuid.uuid4())
        keeper_map[keeper_text] = uid
        code = f"KP-{keeper_text[:20]}"
        f.write(f"INSERT INTO companies (company_id, company_code, company_name, company_type) VALUES ("
                f"'{uid}', {esc(code)}, {esc(keeper_text)}, '{{VENDOR}}'"
                f") ON CONFLICT (company_code) DO NOTHING;\n")
        return f"'{uid}'"

    # ======================================================================
    # [4] MOLDDESIGN → products + mold_masters + design_revisions
    # ======================================================================
    f.write("-- [4] DESIGNS -> products, mold_masters, design_revisions\n")
    default_comp = list(comp_map.values())[0] if comp_map else None

    for r in read_csv("molddesign.csv"):
        oid = r.get("MoldDesignID")
        if not oid: continue

        prod_id = str(uuid.uuid4())
        master_id = str(uuid.uuid4())
        rev_id = str(uuid.uuid4())

        design_map[oid] = {
            'product_id': prod_id,
            'mold_master_id': master_id,
            'design_rev_id': rev_id,
        }

        d_code = r.get("MoldDesignCode") or f"DSGN-{oid}"
        d_name = r.get("MoldDesignName") or d_code
        cust_uid = comp_map.get(r.get("CustomerID"))
        cust_sql = f"'{cust_uid}'" if cust_uid else ("'" + default_comp + "'" if default_comp else "NULL")

        # -- Product
        f.write(f"INSERT INTO products (product_id, product_code, product_name, "
                f"company_id, pocket_count, legacy_id) VALUES ("
                f"'{prod_id}', {esc(d_code)}, {esc(r.get('CustomerTrayName') or d_name)}, "
                f"{cust_sql}, {integer(r.get('PocketNumbers'))}, {esc(oid)}"
                f") ON CONFLICT DO NOTHING;\n")

        # -- Mold Master
        f.write(f"INSERT INTO mold_masters (mold_master_id, mold_master_code, mold_master_name, "
                f"company_id, product_id, legacy_id) VALUES ("
                f"'{master_id}', {esc(d_code)}, {esc(d_name)}, "
                f"{cust_sql}, '{prod_id}', {esc(oid)}"
                f") ON CONFLICT DO NOTHING;\n")

        # -- Design Revision (ALL technical specs)
        legacy_specs = to_json({
            'legacy_tray_id': r.get('TrayID'),
            'legacy_design_master_id': r.get('DesignMasterID'),
            'version_note': r.get('VersionNote'),
        })

        f.write(f"INSERT INTO design_revisions (revision_id, design_code, mold_master_id, "
                f"revision_number, status, "
                f"design_length, design_width, design_height, design_depth, design_weight, "
                f"cutline_length, cutline_width, pitch_mm, pocket_numbers, cavity_count, "
                f"corner_r, chamfer_c, undercut_spec, under_depth, draft_angle, "
                f"orientation, setup_type, has_plug, has_separate_cutter, "
                f"plastic_type_designed, customer_tray_name, tray_info, "
                f"customer_drawing_no, customer_equipment_no, text_content, "
                f"data_input_date, version_note, legacy_id, legacy_specs) VALUES ("
                f"'{rev_id}', {esc(d_code)}, '{master_id}', "
                f"0, 'APPROVED', "
                f"{num(r.get('MoldDesignLength'))}, {num(r.get('MoldDesignWidth'))}, "
                f"{num(r.get('MoldDesignHeight'))}, {num(r.get('MoldDesignDepth'))}, "
                f"{num(r.get('MoldDesignWeight'))}, "
                f"{num(r.get('CutlineX'))}, {num(r.get('CutlineY'))}, "
                f"{num(r.get('Pitch'))}, {integer(r.get('PocketNumbers'))}, "
                f"{integer(r.get('PieceCount'))}, "
                f"{esc(r.get('CornerR'))}, {esc(r.get('ChamferC'))}, "
                f"{esc(r.get('UnderAngle'))}, {num(r.get('UnderDepth'))}, "
                f"{esc(r.get('DraftAngle'))}, "
                f"{esc(r.get('MoldOrientation'))}, {esc(r.get('MoldSetupType'))}, "
                f"{boolean(r.get('Plug'))}, {boolean(r.get('SeparateCutter'))}, "
                f"{esc(r.get('DesignForPlasticType'))}, {esc(r.get('CustomerTrayName'))}, "
                f"{esc(r.get('TrayInfoForMoldDesign'))}, "
                f"{esc(r.get('CustomerDrawingNo'))}, {esc(r.get('CustomerEquipmentNo'))}, "
                f"{esc(r.get('TextContent'))}, "
                f"{esc(r.get('DataInput'))}, {esc(r.get('VersionNote'))}, "
                f"{esc(oid)}, {legacy_specs}"
                f") ON CONFLICT DO NOTHING;\n")
    f.write("\n")

    # ======================================================================
    # [5] MOLDS -> mold_masters, mold_revisions, physical_molds
    # ======================================================================
    f.write("-- [5] MOLDS -> mold_masters, mold_revisions, physical_molds\n")
    mold_revision_map = {}  # (master_id, m_code) -> mrev_id
    for r in read_csv("molds.csv"):
        oid = r.get("MoldID")
        if not oid: continue

        d_id = r.get("MoldDesignID")
        m_code = r.get("MoldCode") or f"MOLD-{oid}"
        m_name = r.get("MoldName") or m_code
        cust_uid = comp_map.get(r.get("CustomerID"))
        cust_sql = f"'{cust_uid}'" if cust_uid else "NULL"

        # Resolve design mapping
        if d_id and d_id in design_map:
            d_info = design_map[d_id]
            master_id = d_info['mold_master_id']
            rev_id = d_info['design_rev_id']
            prod_id = d_info['product_id']
        else:
            # Auto-generate dummy design
            prod_id = str(uuid.uuid4())
            master_id = str(uuid.uuid4())
            rev_id = str(uuid.uuid4())
            dummy_note = "Auto-generated: no design data in legacy"

            f.write(f"INSERT INTO products (product_id, product_code, product_name, company_id, legacy_id) VALUES ("
                    f"'{prod_id}', {esc('AUTO-'+m_code)}, {esc(dummy_note)}, {cust_sql}, {esc(oid+'-auto')}"
                    f") ON CONFLICT DO NOTHING;\n")
            f.write(f"INSERT INTO mold_masters (mold_master_id, mold_master_code, mold_master_name, "
                    f"company_id, product_id, legacy_id) VALUES ("
                    f"'{master_id}', {esc('AUTO-'+m_code)}, {esc(dummy_note)}, {cust_sql}, '{prod_id}', "
                    f"{esc(oid+'-auto')}) ON CONFLICT DO NOTHING;\n")
            f.write(f"INSERT INTO design_revisions (revision_id, design_code, mold_master_id, "
                    f"revision_number, status, version_note, legacy_id) VALUES ("
                    f"'{rev_id}', {esc('AUTO-'+m_code)}, '{master_id}', 0, 'APPROVED', "
                    f"{esc(dummy_note)}, {esc(oid+'-auto')}) ON CONFLICT DO NOTHING;\n")

        phys_id = str(uuid.uuid4())

        # Rack layer
        rl_uid = rl_map.get(r.get("RackLayerID"))
        rl_sql = f"'{rl_uid}'" if rl_uid else "NULL"

        # Keeper company
        keeper_sql = get_keeper_id(r.get("KeeperCompany"))

        # Legacy specs
        legacy = to_json({
            'legacy_revision_id': r.get('MoldRevisionID'),
            'legacy_job_id': r.get('JobID'),
            'legacy_tray_id': r.get('TrayID'),
            'legacy_item_type': r.get('ItemTypeID'),
        })

        rev_key = (master_id, m_code)
        if rev_key not in mold_revision_map:
            mrev_id = str(uuid.uuid4())
            mold_revision_map[rev_key] = mrev_id
            f.write(f"INSERT INTO mold_revisions (revision_id, mold_master_id, design_revision_id, "
                    f"revision_code, revision_name, is_active, legacy_id) VALUES ("
                    f"'{mrev_id}', '{master_id}', '{rev_id}', "
                    f"{esc(m_code)}, {esc(m_name)}, true, {esc(oid)}"
                    f") ON CONFLICT DO NOTHING;\n")
        
        mrev_id = mold_revision_map[rev_key]

        # Physical Mold (skip rack_layer + keeper FK to avoid errors, update later)
        f.write(f"INSERT INTO physical_molds (physical_mold_id, system_code, display_name, "
                f"mold_revision_id, "
                f"actual_length_mm, actual_width_mm, actual_height_mm, actual_weight, "
                f"device_status, usage_status, "
                f"mold_entry_date, returned_date, disposed_date, "
                f"on_checklist, notes, legacy_id, legacy_specs) VALUES ("
                f"'{phys_id}', {esc(m_code)}, {esc(m_name)}, '{mrev_id}', "
                f"{num(r.get('MoldLengthModified'))}, {num(r.get('MoldWidthModified'))}, "
                f"{num(r.get('MoldHeightModified'))}, {num(r.get('MoldWeight'))}, "
                f"{esc(r.get('DeviceStatus') or 'ACTIVE')}, {esc(r.get('MoldUsageStatus') or 'IN_STOCK')}, "
                f"{esc(r.get('MoldEntry'))}, {esc(r.get('MoldReturnedDate'))}, {esc(r.get('MoldDisposedDate'))}, "
                f"{boolean(r.get('MoldOnCheckList'))}, {esc(r.get('MoldNotes'))}, "
                f"{esc(oid)}, {legacy}"
                f") ON CONFLICT DO NOTHING;\n")
    f.write("\n")

    # ======================================================================
    # [6] CUTTERS → cutter_masters + cutters
    # ======================================================================
    f.write("-- [6] CUTTERS -> cutter_masters, cutters\n")
    cutter_master_map = {}  # design_code -> master_id

    for r in read_csv("cutters.csv"):
        oid = r.get("CutterID")
        if not oid: continue

        c_no = r.get("CutterNo") or f"CUT-{oid}"
        c_name = r.get("CutterName") or c_no
        c_design_code = r.get("CutterDesignCode") or r.get("CutterCode") or c_no
        cust_uid = comp_map.get(r.get("CustomerID"))
        cust_sql = f"'{cust_uid}'" if cust_uid else "NULL"

        # Get or create cutter master
        d_id = r.get("MoldDesignID")
        d_info = design_map.get(d_id) if d_id else None
        master_link = f"'{d_info['mold_master_id']}'" if d_info else "NULL"

        if c_design_code not in cutter_master_map:
            cm_id = str(uuid.uuid4())
            cutter_master_map[c_design_code] = cm_id
            f.write(f"INSERT INTO cutter_masters (cutter_master_id, cutter_master_code, cutter_master_name, "
                    f"mold_master_id, company_id, legacy_id) VALUES ("
                    f"'{cm_id}', {esc(c_design_code)}, {esc(c_name)}, "
                    f"{master_link}, {cust_sql}, {esc(r.get('CutterMasterID') or oid)}"
                    f") ON CONFLICT DO NOTHING;\n")
        cm_id = cutter_master_map[c_design_code]

        # Design revision link
        rev_link = f"'{d_info['design_rev_id']}'" if d_info else "NULL"

        # Rack layer + Keeper
        rl_uid = rl_map.get(r.get("RackLayerID"))
        rl_sql = f"'{rl_uid}'" if rl_uid else "NULL"
        keeper_sql = get_keeper_id(r.get("KeeperCompany"))

        # Legacy specs
        legacy = to_json({
            'shared_molds': r.get('MoldShared'),
            'detail': r.get('CutterDetail'),
            'description': r.get('Description'),
            'presence': r.get('CutterPresence'),
            'dim': r.get('CutterDim'),
            'entry_date': r.get('CutterEntry'),
            'manufacture_date': r.get('CutterManufactureDate'),
        })

        # Physical cutter (skip rack_layer + keeper FK to avoid errors)
        f.write(f"INSERT INTO cutters (cutter_id, cutter_no, cutter_name, cutter_master_id, "
                f"cutter_design_code, company_id, design_revision_id, "
                f"cavity_count, pitch_mm, "
                f"cutter_length_mm, cutter_width_mm, cutter_height_mm, "
                f"corner_r, chamfer_c, cutline_length, cutline_width, "
                f"post_cut_length, post_cut_width, "
                f"cutter_type, plastic_cut_type, "
                f"usage_status, notes, legacy_id, legacy_specs) VALUES ("
                f"'{str(uuid.uuid4())}', {esc(c_no)}, {esc(c_name)}, '{cm_id}', "
                f"{esc(c_design_code)}, {cust_sql}, {rev_link}, "
                f"{integer(r.get('BladeCount'))}, {num(r.get('Pitch'))}, "
                f"{num(r.get('CutterLength'))}, {num(r.get('CutterWidth'))}, "
                f"{num(r.get('CutterHeight'))}, "
                f"{esc(r.get('CutterCorner'))}, {esc(r.get('CutterChamfer'))}, "
                f"{num(r.get('CutlineLength'))}, {num(r.get('CutlineWidth'))}, "
                f"{num(r.get('PostCutLength'))}, {num(r.get('PostCutWidth'))}, "
                f"{esc(r.get('CutterType'))}, {esc(r.get('PlasticCutType'))}, "
                f"{esc(r.get('UsageStatus') or 'ACTIVE')}, {esc(r.get('CutterNote'))}, "
                f"{esc(oid)}, {legacy}"
                f") ON CONFLICT DO NOTHING;\n")
    f.write("\n")

    f.write("COMMIT;\n")
    f.close()

    print(f"\n=== Done! Output: {OUTPUT_FILE} ===")
    print(f"Companies: {len(comp_map)} + {len(keeper_map)} keeper companies")
    print(f"Employees: {len(emp_map)}")
    print(f"Racks: {len(rack_map)}, Layers: {len(rl_map)}")
    print(f"Designs: {len(design_map)}")
    print(f"Cutter Masters: {len(cutter_master_map)}")

if __name__ == "__main__":
    main()
